# -*- coding: utf-8 -*-
"""summer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GjjyXcO3bBgVuQ2ZfzI5NJW5uSmT-xbk

**1. In how many cities Summer Olympics is held so far?**
"""

import pandas as pd

df = pd.read_csv("summer.csv")

ans=[]
for i in df['City'].unique():
  ans.append([i,len(df[df['City']  == i])])

TC= len(ans)
city = pd.DataFrame(ans,columns = ['City','Freq'])
print("Total number of cities are",TC)

ans

"""**2. Which sport is having most number of Gold Medals so far? (Top 5)**"""

df_gold_medals = df[df['Medal'] == 'Gold']['Sport']
df_gold_medals

gold_medals=[]
for i in df_gold_medals.unique():
  gold_medals.append([i,len(df[df['Sport']  == i])])


df_gold_medals = pd.DataFrame(gold_medals,columns = ['Sport','No of Gold Medals'])

df_gold_medals.sort_values(by = 'No of Gold Medals', ascending=False).head()

df_gold_medals.sort_values(by = 'No of Gold Medals', ascending=False).head().plot(x='Sport' , y='No of Gold Medals', kind = 'bar', figsize = (10,5))

"""**3. Which sport is having most number of medals so far? (Top 5)**"""

lf=df

del lf['Year']
del lf['City']
del lf['Discipline']
del lf['Athlete']
del lf['Country']
del lf['Gender']
del lf['Event']

a = len(lf[lf['Medal'] == 'Gold'])
b = len(lf[lf['Medal'] == 'Silver'])
c = len(lf[lf['Medal'] == 'Bronze'])

df = pd.read_csv("summer.csv")

a+b+c == len(df)

res=[]
for i in lf['Sport'].unique():
  res.append([i,len(lf[lf['Sport']==i])])
res

lst=lf.values.tolist()
lst1=[]
for i in lst:
  lst1.append(i[0])
lst2 = list(set(lst1))

count=[]
for i in lst2:
  count.append([i,lst1.count(i)])

count = pd.DataFrame(count,columns = ['Sport','No of Medals'])

count.sort_values(by = 'No of Medals', ascending=False).head().plot(x='Sport',y='No of Medals', kind = 'bar' , figsize = (10,5))

"""**4. Which player has won most number of medals? (Top 5)**"""

lst = df['Athlete'].values.tolist()
lst1=list(set(lst))

cnt = []

for i in lst1:
  cnt.append([i,lst.count(i)])

cnt = pd.DataFrame(cnt,columns = ['Athlete','No of Medals'])

cnt.sort_values(by = 'No of Medals', ascending = False).head().plot(x = 'Athlete', y = 'No of Medals', kind = 'bar', figsize = (10,5))

"""**5. Which player has won most number Gold Medals of medals? (Top 5)**"""

plr_gold_medals = df[df['Medal'] == 'Gold']
p_gold_medals=[]
for i in plr_gold_medals['Athlete'].unique():
  p_gold_medals.append([i,len(df[df['Athlete']  == i])])


p_gold_medals = pd.DataFrame(p_gold_medals,columns = ['Player','No of Gold Medals'])

p_gold_medals.sort_values(by = 'No of Gold Medals', ascending=False).head().plot(x='Player' , y='No of Gold Medals', kind = 'bar', figsize = (10,5))

"""**6. In which year India won first Gold Medal in Summer Olympics?**"""

ind = df[df['Country'] == 'IND']
ind = ind[ind['Medal'] == 'Gold']
ind = ind['Year']
ind_gold_yrs = ind.values.tolist()
ind_gold_yrs = list(set(ind_gold_yrs))
ind_gold_yrs.sort()

print('India won the first gold medal in the year -',ind_gold_yrs[0])

"""**7. Which event is most popular in terms on number of players? (Top 5)**"""

lf = df
del lf['Year']
del lf['City']
del lf['Discipline']
del lf['Sport']
del lf['Country']
del lf['Gender']
del lf['Medal']

l = list(df['Event'].unique())
l1 = df.values.tolist()
l = list(set(l))
l2=[]
for i in l1:
  l2.append(i[1])

pp_event=[]
for i in l:
  pp_event.append([i,l2.count(i)])

pp_event = pd.DataFrame(pp_event,columns = ['Event','No of Players'])

pp_event.sort_values(by = 'No of Players', ascending = False).head().plot(x = 'Event' , y='No of Players', kind ='bar' , figsize = (10,5))

"""**8. Which sport is having most female Gold Medalists? (Top 5)**"""

df = pd.read_csv("summer.csv")

df = df[df['Gender'] == 'Women'][df['Medal'] == 'Gold']['Sport']


fgm = df.values.tolist()
fgm
fgm1 = list(set(fgm))

fgm_cnt = []
for i in fgm1:
  fgm_cnt.append([i,fgm.count(i)])

fgm_cnt = pd.DataFrame(fgm_cnt, columns =['Sport', 'No of Female Gold Medalists'])

fgm_cnt.sort_values(by = 'No of Female Gold Medalists', ascending = False).head().plot(x='Sport', y='No of Female Gold Medalists', kind = 'bar', figsize = (10,5))

